[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "h-template"
version = "1.0.0b1"
description = "Experimental project for generating HTML in Python using Pydantic BaseModel."
readme = "README.md"
license = "ISC"
authors = [
    { name = "Jeff Triplett", email = "jeff.triplett@gmail.com" }
]
keywords = ["AWS", "EC2", "metadata"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: ISC License (ISCL)",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
requires-python = ">=3.10"
dependencies = [
    "pydantic>=2.0.0",
]

[dependency-groups]
dev = [
    "pytest",
    "pytest-cov",
]

[project.urls]
Homepage = "https://github.com/jefftriplett/h-template"
Changelog = "https://github.com/jefftriplett/h-template/blob/main/HISTORY.md"

[tool.hatch.build.targets.wheel]
packages = ["src/h.py"]

[tool.flake8]
max-line-length = 80
select = ["C", "E", "F", "W", "B", "B950"]
ignore = ["E501", "W503"]

[tool.isort]
include_trailing_comma = true
force_grid_wrap = 0
known_first_party = ["h"]
line_length = 88
multi_line_output = 3
use_parentheses = true
